config/routes.rb
Chsdesk::Application.routes.draw do
  resources :societies
  resources :transaction_type_masters
  resources :ledger_details
  resources :committees
  resources :bills
  resources :bill_transactions
  resources :bill_setups
  resources :bill_details
  resources :account_transactions
  resources :account_groups
  resources :password_resets
  resources :members
  resources :sessions
  resources :users
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "home#index"

  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/unitsetup',  :to => 'units#index'
  match '/master',  :to => 'societies#index'
  match '/assignmember',  :to => 'members#index'

 match '/transaction_type_masters',  :to => 'transaction_type_masters#index'
 match '/ledger_details',  :to => 'ledger_details#index'
 match '/committees',  :to => 'committees#index'
 match '/bills',  :to => 'bills#index'
 match '/bill_transactions',  :to => 'bill_transactions#index'
 match '/bill_setups',  :to => 'bill_setups#index'
 match '/bill_details',  :to => 'bill_details#index'
 match '/account_transactions',  :to => 'account_transactions#index'
 match '/account_groups',  :to => 'account_groups#index'

end

app/controllers/bill_transactions_controller.rb
class BillTransactionsController < ApplicationController
  # GET /bill_transactions
  # GET /bill_transactions.json
  def index
    @bill_transactions = BillTransaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bill_transactions }
    end
  end

  # GET /bill_transactions/1
  # GET /bill_transactions/1.json
  def show
    @bill_transaction = BillTransaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @bill_transaction }
    end
  end

  # GET /bill_transactions/new
  # GET /bill_transactions/new.json
  def new
    @bill_transaction = BillTransaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bill_transaction }
    end
  end

  # GET /bill_transactions/1/edit
  def edit
    @bill_transaction = BillTransaction.find(params[:id])
  end

  # POST /bill_transactions
  # POST /bill_transactions.json
  def create
    @bill_transaction = BillTransaction.new(params[:bill_transaction])

    respond_to do |format|
      if @bill_transaction.save
        format.html { redirect_to @bill_transaction, :notice => 'Bill transaction was successfully created.' }
        format.json { render :json => @bill_transaction, :status => :created, :location => @bill_transaction }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bill_transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bill_transactions/1
  # PUT /bill_transactions/1.json
  def update
    @bill_transaction = BillTransaction.find(params[:id])

    respond_to do |format|
      if @bill_transaction.update_attributes(params[:bill_transaction])
        format.html { redirect_to @bill_transaction, :notice => 'Bill transaction was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bill_transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_transactions/1
  # DELETE /bill_transactions/1.json
  def destroy
    @bill_transaction = BillTransaction.find(params[:id])
    @bill_transaction.destroy

    respond_to do |format|
      format.html { redirect_to bill_transactions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/bill_transactions_helper.rb
module BillTransactionsHelper
end

app/views/bill_transactions/_form.html.erb
<%= form_for(@bill_transaction) do |f| %>
  <% if @bill_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill_transaction.errors.count, "error") %> prohibited this bill_transaction from being saved:</h2>

      <ul>
      <% @bill_transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bill_id %><br />
    <%= f.number_field :bill_id %>
  </div>
  <div class="field">
    <%= f.label :transaction_date %><br />
    <%= f.datetime_select :transaction_date %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.check_box :email %>
  </div>
  <div class="field">
    <%= f.label :pdf %><br />
    <%= f.check_box :pdf %>
  </div>
  <div class="field">
    <%= f.label :user_member_id %><br />
    <%= f.number_field :user_member_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_transactions/edit.html.erb
<h1>Editing bill_transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill_transaction %> |
<%= link_to 'Back', bill_transactions_path %>

app/views/bill_transactions/index.html.erb
<h1>Listing bill_transactions</h1>

<table>
  <tr>
    <th>Bill</th>
    <th>Transaction date</th>
    <th>Email</th>
    <th>Pdf</th>
    <th>User member</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bill_transactions.each do |bill_transaction| %>
  <tr>
    <td><%= bill_transaction.bill_id %></td>
    <td><%= bill_transaction.transaction_date %></td>
    <td><%= bill_transaction.email %></td>
    <td><%= bill_transaction.pdf %></td>
    <td><%= bill_transaction.user_member_id %></td>
    <td><%= link_to 'Show', bill_transaction %></td>
    <td><%= link_to 'Edit', edit_bill_transaction_path(bill_transaction) %></td>
    <td><%= link_to 'Destroy', bill_transaction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill transaction', new_bill_transaction_path %>

app/views/bill_transactions/new.html.erb
<h1>New bill_transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_transactions_path %>

app/views/bill_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bill:</b>
  <%= @bill_transaction.bill_id %>
</p>

<p>
  <b>Transaction date:</b>
  <%= @bill_transaction.transaction_date %>
</p>

<p>
  <b>Email:</b>
  <%= @bill_transaction.email %>
</p>

<p>
  <b>Pdf:</b>
  <%= @bill_transaction.pdf %>
</p>

<p>
  <b>User member:</b>
  <%= @bill_transaction.user_member_id %>
</p>


<%= link_to 'Edit', edit_bill_transaction_path(@bill_transaction) %> |
<%= link_to 'Back', bill_transactions_path %>