config/routes.rb
Chsdesk::Application.routes.draw do
  resources :societies
  resources :transaction_type_masters
  resources :ledger_details
  resources :committees
  resources :bills
  resources :bill_transactions
  resources :bill_setups
  resources :bill_details
  resources :account_transactions
  resources :account_groups
  resources :password_resets
  resources :members
  resources :sessions
  resources :users
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "home#index"

  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/unitsetup',  :to => 'units#index'
  match '/master',  :to => 'societies#index'
  match '/assignmember',  :to => 'members#index'

 match '/transaction_type_masters',  :to => 'transaction_type_masters#index'
 match '/ledger_details',  :to => 'ledger_details#index'
 match '/committees',  :to => 'committees#index'
 match '/bills',  :to => 'bills#index'
 match '/bill_transactions',  :to => 'bill_transactions#index'
 match '/bill_setups',  :to => 'bill_setups#index'
 match '/bill_details',  :to => 'bill_details#index'
 match '/account_transactions',  :to => 'account_transactions#index'
 match '/account_groups',  :to => 'account_groups#index'

end

app/models/bill_setup.rb
class BillSetup < ActiveRecord::Base
end
# == Schema Information
#
# Table name: bill_setups
#
#  bill_setup_id    :integer(4)      not null, primary key
#  society_id       :integer(4)
#  head_name        :string(100)
#  rate_sqft_month  :integer(2)
#  rate_unit_month  :integer(2)
#  service_tax_pct  :integer(2)
#  days_to_discount :integer(4)
#  discount_pct     :integer(2)
#  created_at       :datetime
#  updated_at       :datetime
#

app/controllers/bill_setups_controller.rb
class BillSetupsController < ApplicationController
  # GET /bill_setups
  # GET /bill_setups.json
  def index
    @bill_setups = BillSetup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bill_setups }
    end
  end

  # GET /bill_setups/1
  # GET /bill_setups/1.json
  def show
    @bill_setup = BillSetup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @bill_setup }
    end
  end

  # GET /bill_setups/new
  # GET /bill_setups/new.json
  def new
    @bill_setup = BillSetup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bill_setup }
    end
  end

  # GET /bill_setups/1/edit
  def edit
    @bill_setup = BillSetup.find(params[:id])
  end

  # POST /bill_setups
  # POST /bill_setups.json
  def create
    @bill_setup = BillSetup.new(params[:bill_setup])

    respond_to do |format|
      if @bill_setup.save
        format.html { redirect_to @bill_setup, :notice => 'Bill setup was successfully created.' }
        format.json { render :json => @bill_setup, :status => :created, :location => @bill_setup }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bill_setup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bill_setups/1
  # PUT /bill_setups/1.json
  def update
    @bill_setup = BillSetup.find(params[:id])

    respond_to do |format|
      if @bill_setup.update_attributes(params[:bill_setup])
        format.html { redirect_to @bill_setup, :notice => 'Bill setup was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bill_setup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_setups/1
  # DELETE /bill_setups/1.json
  def destroy
    @bill_setup = BillSetup.find(params[:id])
    @bill_setup.destroy

    respond_to do |format|
      format.html { redirect_to bill_setups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/bill_setups_helper.rb
module BillSetupsHelper
end

app/views/bill_setups/_form.html.erb
<%= form_for(@bill_setup) do |f| %>
  <% if @bill_setup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill_setup.errors.count, "error") %> prohibited this bill_setup from being saved:</h2>

      <ul>
      <% @bill_setup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :society_id %><br />
    <%= f.number_field :society_id %>
  </div>
  <div class="field">
    <%= f.label :head_name %><br />
    <%= f.text_field :head_name %>
  </div>
  <div class="field">
    <%= f.label :rate_sqft_month %><br />
    <%= f.text_field :rate_sqft_month %>
  </div>
  <div class="field">
    <%= f.label :rate_unit_month %><br />
    <%= f.text_field :rate_unit_month %>
  </div>
  <div class="field">
    <%= f.label :service_tax_pct %><br />
    <%= f.text_field :service_tax_pct %>
  </div>
  <div class="field">
    <%= f.label :days_to_discount %><br />
    <%= f.number_field :days_to_discount %>
  </div>
  <div class="field">
    <%= f.label :discount_pct %><br />
    <%= f.text_field :discount_pct %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_setups/edit.html.erb
<h1>Editing bill_setup</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill_setup %> |
<%= link_to 'Back', bill_setups_path %>

app/views/bill_setups/index.html.erb
<h1>Listing bill_setups</h1>

<table>
  <tr>
    <th>Society</th>
    <th>Head name</th>
    <th>Rate sqft month</th>
    <th>Rate unit month</th>
    <th>Service tax pct</th>
    <th>Days to discount</th>
    <th>Discount pct</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bill_setups.each do |bill_setup| %>
  <tr>
    <td><%= bill_setup.society_id %></td>
    <td><%= bill_setup.head_name %></td>
    <td><%= bill_setup.rate_sqft_month %></td>
    <td><%= bill_setup.rate_unit_month %></td>
    <td><%= bill_setup.service_tax_pct %></td>
    <td><%= bill_setup.days_to_discount %></td>
    <td><%= bill_setup.discount_pct %></td>
    <td><%= link_to 'Show', bill_setup %></td>
    <td><%= link_to 'Edit', edit_bill_setup_path(bill_setup) %></td>
    <td><%= link_to 'Destroy', bill_setup, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill setup', new_bill_setup_path %>

app/views/bill_setups/new.html.erb
<h1>New bill_setup</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_setups_path %>

app/views/bill_setups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Society:</b>
  <%= @bill_setup.society_id %>
</p>

<p>
  <b>Head name:</b>
  <%= @bill_setup.head_name %>
</p>

<p>
  <b>Rate sqft month:</b>
  <%= @bill_setup.rate_sqft_month %>
</p>

<p>
  <b>Rate unit month:</b>
  <%= @bill_setup.rate_unit_month %>
</p>

<p>
  <b>Service tax pct:</b>
  <%= @bill_setup.service_tax_pct %>
</p>

<p>
  <b>Days to discount:</b>
  <%= @bill_setup.days_to_discount %>
</p>

<p>
  <b>Discount pct:</b>
  <%= @bill_setup.discount_pct %>
</p>


<%= link_to 'Edit', edit_bill_setup_path(@bill_setup) %> |
<%= link_to 'Back', bill_setups_path %>