config/routes.rb
Chsdesk::Application.routes.draw do
  resources :societies
  resources :transaction_type_masters
  resources :ledger_details
  resources :committees
  resources :bills
  resources :bill_transactions
  resources :bill_setups
  resources :bill_details
  resources :account_transactions
  resources :account_groups
  resources :password_resets
  resources :members
  resources :sessions
  resources :users
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "home#index"

  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/unitsetup',  :to => 'units#index'
  match '/master',  :to => 'societies#index'
  match '/assignmember',  :to => 'members#index'

 match '/transaction_type_masters',  :to => 'transaction_type_masters#index'
 match '/ledger_details',  :to => 'ledger_details#index'
 match '/committees',  :to => 'committees#index'
 match '/bills',  :to => 'bills#index'
 match '/bill_transactions',  :to => 'bill_transactions#index'
 match '/bill_setups',  :to => 'bill_setups#index'
 match '/bill_details',  :to => 'bill_details#index'
 match '/account_transactions',  :to => 'account_transactions#index'
 match '/account_groups',  :to => 'account_groups#index'

end

app/models/transaction_type_master.rb
class TransactionTypeMaster < ActiveRecord::Base
end
# == Schema Information
#
# Table name: transaction_type_masters
#
#  transaction_type_id     :integer(4)      not null, primary key
#  transaction_type        :string(45)
#  transaction_type_prefix :string(45)
#  created_at              :datetime
#  updated_at              :datetime
#

app/controllers/transaction_type_masters_controller.rb
class TransactionTypeMastersController < ApplicationController
  # GET /transaction_type_masters
  # GET /transaction_type_masters.json
  def index
    @transaction_type_masters = TransactionTypeMaster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @transaction_type_masters }
    end
  end

  # GET /transaction_type_masters/1
  # GET /transaction_type_masters/1.json
  def show
    @transaction_type_master = TransactionTypeMaster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @transaction_type_master }
    end
  end

  # GET /transaction_type_masters/new
  # GET /transaction_type_masters/new.json
  def new
    @transaction_type_master = TransactionTypeMaster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @transaction_type_master }
    end
  end

  # GET /transaction_type_masters/1/edit
  def edit
    @transaction_type_master = TransactionTypeMaster.find(params[:id])
  end

  # POST /transaction_type_masters
  # POST /transaction_type_masters.json
  def create
    @transaction_type_master = TransactionTypeMaster.new(params[:transaction_type_master])

    respond_to do |format|
      if @transaction_type_master.save
        format.html { redirect_to @transaction_type_master, :notice => 'Transaction type master was successfully created.' }
        format.json { render :json => @transaction_type_master, :status => :created, :location => @transaction_type_master }
      else
        format.html { render :action => "new" }
        format.json { render :json => @transaction_type_master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transaction_type_masters/1
  # PUT /transaction_type_masters/1.json
  def update
    @transaction_type_master = TransactionTypeMaster.find(params[:id])

    respond_to do |format|
      if @transaction_type_master.update_attributes(params[:transaction_type_master])
        format.html { redirect_to @transaction_type_master, :notice => 'Transaction type master was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @transaction_type_master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_type_masters/1
  # DELETE /transaction_type_masters/1.json
  def destroy
    @transaction_type_master = TransactionTypeMaster.find(params[:id])
    @transaction_type_master.destroy

    respond_to do |format|
      format.html { redirect_to transaction_type_masters_url }
      format.json { head :ok }
    end
  end
end

app/helpers/transaction_type_masters_helper.rb
module TransactionTypeMastersHelper
end

app/views/transaction_type_masters/_form.html.erb
<%= form_for(@transaction_type_master) do |f| %>
  <% if @transaction_type_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction_type_master.errors.count, "error") %> prohibited this transaction_type_master from being saved:</h2>

      <ul>
      <% @transaction_type_master.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_type %><br />
    <%= f.text_field :transaction_type %>
  </div>
  <div class="field">
    <%= f.label :transaction_type_prefix %><br />
    <%= f.text_field :transaction_type_prefix %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transaction_type_masters/edit.html.erb
<h1>Editing transaction_type_master</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction_type_master %> |
<%= link_to 'Back', transaction_type_masters_path %>

app/views/transaction_type_masters/index.html.erb
<h1>Listing transaction_type_masters</h1>

<table>
  <tr>
    <th>Transaction type</th>
    <th>Transaction type prefix</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transaction_type_masters.each do |transaction_type_master| %>
  <tr>
    <td><%= transaction_type_master.transaction_type %></td>
    <td><%= transaction_type_master.transaction_type_prefix %></td>
    <td><%= link_to 'Show', transaction_type_master %></td>
    <td><%= link_to 'Edit', edit_transaction_type_master_path(transaction_type_master) %></td>
    <td><%= link_to 'Destroy', transaction_type_master, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction type master', new_transaction_type_master_path %>

app/views/transaction_type_masters/new.html.erb
<h1>New transaction_type_master</h1>

<%= render 'form' %>

<%= link_to 'Back', transaction_type_masters_path %>

app/views/transaction_type_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Transaction type:</b>
  <%= @transaction_type_master.transaction_type %>
</p>

<p>
  <b>Transaction type prefix:</b>
  <%= @transaction_type_master.transaction_type_prefix %>
</p>


<%= link_to 'Edit', edit_transaction_type_master_path(@transaction_type_master) %> |
<%= link_to 'Back', transaction_type_masters_path %>