config/routes.rb
Chsdesk::Application.routes.draw do
  resources :societies
  resources :transaction_type_masters
  resources :ledger_details
  resources :committees
  resources :bills
  resources :bill_transactions
  resources :bill_setups
  resources :bill_details
  resources :account_transactions
  resources :account_groups
  resources :password_resets
  resources :members
  resources :sessions
  resources :users
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "home#index"

  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/unitsetup',  :to => 'units#index'
  match '/master',  :to => 'societies#index'
  match '/assignmember',  :to => 'members#index'

 match '/transaction_type_masters',  :to => 'transaction_type_masters#index'
 match '/ledger_details',  :to => 'ledger_details#index'
 match '/committees',  :to => 'committees#index'
 match '/bills',  :to => 'bills#index'
 match '/bill_transactions',  :to => 'bill_transactions#index'
 match '/bill_setups',  :to => 'bill_setups#index'
 match '/bill_details',  :to => 'bill_details#index'
 match '/account_transactions',  :to => 'account_transactions#index'
 match '/account_groups',  :to => 'account_groups#index'

end

app/models/committee.rb
class Committee < ActiveRecord::Base
end
# == Schema Information
#
# Table name: committees
#
#  member_id   :integer(4)      not null
#  society_id  :integer(4)      not null
#  desgination :string(100)     not null
#  start_date  :date            not null
#  end_date    :date            not null
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  # GET /committees
  # GET /committees.json
  def index
    @committees = Committee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @committees }
    end
  end

  # GET /committees/1
  # GET /committees/1.json
  def show
    @committee = Committee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @committee }
    end
  end

  # GET /committees/new
  # GET /committees/new.json
  def new
    @committee = Committee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @committee }
    end
  end

  # GET /committees/1/edit
  def edit
    @committee = Committee.find(params[:id])
  end

  # POST /committees
  # POST /committees.json
  def create
    @committee = Committee.new(params[:committee])

    respond_to do |format|
      if @committee.save
        format.html { redirect_to @committee, :notice => 'Committee was successfully created.' }
        format.json { render :json => @committee, :status => :created, :location => @committee }
      else
        format.html { render :action => "new" }
        format.json { render :json => @committee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /committees/1
  # PUT /committees/1.json
  def update
    @committee = Committee.find(params[:id])

    respond_to do |format|
      if @committee.update_attributes(params[:committee])
        format.html { redirect_to @committee, :notice => 'Committee was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @committee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /committees/1
  # DELETE /committees/1.json
  def destroy
    @committee = Committee.find(params[:id])
    @committee.destroy

    respond_to do |format|
      format.html { redirect_to committees_url }
      format.json { head :ok }
    end
  end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_form.html.erb
<%= form_for(@committee) do |f| %>
  <% if @committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% @committee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.number_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :society_id %><br />
    <%= f.number_field :society_id %>
  </div>
  <div class="field">
    <%= f.label :desgination %><br />
    <%= f.text_field :desgination %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/committees/edit.html.erb
<h1>Editing committee</h1>

<%= render 'form' %>

<%= link_to 'Show', @committee %> |
<%= link_to 'Back', committees_path %>

app/views/committees/index.html.erb
<h1>Listing committees</h1>

<table>
  <tr>
    <th>Member</th>
    <th>Society</th>
    <th>Desgination</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @committees.each do |committee| %>
  <tr>
    <td><%= committee.member_id %></td>
    <td><%= committee.society_id %></td>
    <td><%= committee.desgination %></td>
    <td><%= committee.start_date %></td>
    <td><%= committee.end_date %></td>
    <td><%= link_to 'Show', committee %></td>
    <td><%= link_to 'Edit', edit_committee_path(committee) %></td>
    <td><%= link_to 'Destroy', committee, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Committee', new_committee_path %>

app/views/committees/new.html.erb
<h1>New committee</h1>

<%= render 'form' %>

<%= link_to 'Back', committees_path %>

app/views/committees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Member:</b>
  <%= @committee.member_id %>
</p>

<p>
  <b>Society:</b>
  <%= @committee.society_id %>
</p>

<p>
  <b>Desgination:</b>
  <%= @committee.desgination %>
</p>

<p>
  <b>Start date:</b>
  <%= @committee.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @committee.end_date %>
</p>


<%= link_to 'Edit', edit_committee_path(@committee) %> |
<%= link_to 'Back', committees_path %>